#+TITLE: CV Pavel Rusinský - kompletní
#+AUTHOR: Pavel Rusinský

* Osobní údaje
Jméno: Pavel Rusinský
Datum narození: 7. 2. 1992
Očkován na COVID-19 (pro někoho nyní důležité): ano

* O mně
Team leader, projektový/produktový manažer, markeťák. Vždy se snažím dosáhnout maxima, které mi daná příležitost nabízí.
Začínal jsem svou kariéru jako brigádník v OKAY, který psal produktové popisky pro e-shop. To mne dovedlo k pozici copywritera. Moje nadšení a drobný workholismus mi pomohli k možnosti začít stavět svůj první tým. Ve chvíli, kdy jsem měl pocit, že jsou samostatní, vzal jsem nabídkou majitele na účasti na velkých projektech, které posouvali celou společnost kupředu. Vždy jsem se snažil využít možnost naučit se nové věci a dělat větší. Samozřejmostí pro tyto kroky bylo vědomí, že můj tým bude stále produktivní.

Pak jsem nastoupil do Mergada, kde jsem začal jako konzultant pro klienty a partnery. Objížděl jsem marketingové agentury a srovnávače zboží, abych budoval dobré vztahy. Pomáhal jsem přinášet potřebné informace, které měly pomoci rozvinout náš produkt. Ve volných chvílích jsem se věnoval technické podpoře a specifikování nových funkcí. Díky tomu jsem se dostal k vývojovému týmu. Udělal jsem si kurz Pyladies (jako nadšenec do IT), kde jsem byl první brněnský mužský absolvent. Při odchodu hlavního vývojáře mi bylo nabídnuto místo vedení dev týmu.
Přebral jsem pocizi vedoucího 5 vývojářů a za pár let dokázal poskládat tým 15 odborníků (vývojářů, produkťáků a testerů), kterým naprosto důvěřuji, že jsou schopní náš produkt posouvat.

Ve své kariéře jsem se nikdy nebál výzvy a do všeho se vrhnul po hlavě. Protože co člověk neumí, to se naučí. Nikdy jsem v minulosti jsem nevedl lidi, nepracoval v marketingu a IT, nepřednášel, neškolil a dnes tuto věci beru jako samozřejmou součást mého života. Byla to jízda a doufám, že nekončí.

Ale aby "about me" nebylo jen o pracovních zkušenostech, zkusím dodat nějaké další informace. Většinou se popisuji jako "desetibojař". Rád dělám hodně věcí a neustále zkouším něco nového. Mé aktuální směry jsou chov koní, hlavolamy (sudoku atd.), řezbaření a IT. Možná se to změní, ještě je spousta věcí, které jsem nezkusil.

Nyní čekáme s manželkou prvního potomka, který se má narodit na konci září, a tak je většina mé pozornosti upnuta tímto směrem.

A kdybyste chtěli vědět, co mne poslední dobou nejvíce inspirovalo, tak je to kniha Be obsessed or be average. Grant Cordone je sice blázen, ale spousta jeho myšlenek má hlavu a patu.

Je toho hodně, rád si o všem popovídám osobně.

* Pracovní zkušenosti
Většina pracovní náplně je popsána i v krátké verzi CV.
** okay s.r.o.
*** Copywriter
- tvorba textů pro celý omnichannel (články, radiové spoty, newslettery, grafiky,  billboardy, aj.)
- pracovní nabídku na fulltime jsem dostal jako brigádník
*** Vedoucí PR a copywrintingu
Vedoucí copywritingu
- kompletní strategie a analytika mailingu
- analýza všech textů na e-shopu
- vedení týmu copywriterů
- zodpovědnost za články na e-shopu
- monitoring nových trendů v online i offline prostředí
- propojení moderovaného obsahu webu s cíli společnosti
- návrhy extenzí na podporu brandu (zábavné aplikace, hry, reklamní předměty, aj.)
- spolupráce na kreativní strategii firmy v online i offline prostředí
- koordinace brigádníků

Vedoucí PR
- tvorba PR strategie společností OKAY Holding
- spolupráce s PR agenturou
- komunikace s médii
- tvorba a realizace PR projektů
- monitoring mediálního obrazu společnosti a jeho analýza
- psaní tiskových zpráv
- navazování spolupráce s blogery
- administrativa
- monitoring vnitrofiremního prostředí

*** Projektý manažer a specialista digitální komunikace
Projekty:
- implementace CRM
- vývoj mobilní aplikace a věrnostního programu
- personalizovaná komunikace se zákazníkem napříč formáty
- implementace softwaru pro koordinaci práce oddělení marketingu
- OKAY Maturiťák (několikatýdenní soutěž pro maturanty)
Další náplň práce
- tvorba nových strategií
- analýza obchodních dat

** Mergado technologies s.r.o.
*** Konzultant
- komunikace s klienty a partnery (hlavní náplň práce)
- vyřizovaní požadavků na zákaznické podpoře
- specifikace issues pro vývojáře
- testování software

*** Vedoucí vývoje
- vedení týmu (vývojáři, produktoví manažeři, testeři)
  + koordinace týmu
  + pořádání teambuildingů
  + pravidelné one-to-one o spokojenosti zaměstnanců
  + zařizování kvalitního prostředí pro práci
- implementace procesů a organizace práce
  + zavedení agilních procesů a jejich iterativní vylepšování
  + specifikace projektů a issues pro vývoj
- spolupráce na vedení společnosti
  + rozhodování o směřování produktu a společnosti
  + stanovení a vyhodnocení cílů

* Mimopracovní zkušenosti/Projekty
** Pyladies
Spoluorganizátor a kouč na několika semestrech. Lektor základů Pythonu.
Účastnil jsem také několika PyConů a dalších akcí Pyvce.
** Přednášení
- desítky školení a přednášek o feed marketingu
  + témata např.: Základy feed marketingu, Základy srovnávačů zboží, XML a jeho využítí, Expanze do zahraničí s produktovými feedy,
- přednáška "Jak mluvit s vývojáři"
- přednášení na firemních a vnitrofiremních akcích o novinkách v Mergadu
- krátké technické prezentace na vývojářských akcích
** DoneeCode
Projekt, který zrovna začínám. Již nějakou dobu se věnuji věcem ohledně vývoje a nyní jsem našel online curriculum, které obsahuje vše potřebné k získýní titulu z informatiky (samozřejmě člověk žádný titul nedostane). Ale chci se dále rozvíjet a doplnit si znalosti a tak si tuto "online vysokou" v následujích letech udělám. Svůj progress chci monitorovat pomocí blogu, který právě vytvářím. (Jméno je odkaz na mou teen přezdívku ve spojení s hlavním obsahem).
* Vzdělání
** Gymnázium Hodonín
(2003 - 2012)
Ukončeno maturitní zkouškou.
** Veterinární a farmaceutická univerzita Brno
(2013 - 2015)
Ukončeno ze zdravotních důvodů.
* Dovednosti
** Projektové řízení
*** Agile
- znám principy agile vývoje a implementoval jsem naši vlastní variantu pro DEV tým
*** PRINCE2
- certifikovaný projektový manažer
** Marketing
Mám základní všech marketingových principů, ale exekutivně jsem se věnoval pouze marketingovým strategiím, copywringu, feed marketingu a emailingu.
*** Feed marketing
*** Copywriting
*** Emailing
** Team management/leadership
** Coding
Programování se nyní aktivně nevěnuji, ale to se brzo změní. Viz sekci DoneeCode.
- Python
  + absolvent kurzu Pyladies
  + pár vlastních drobných projektů
- základy C, JS, bash
* Kontakt
Adresa trvalého bydliště: Fr. Vlacha 745, Dubňany 696 03
Korespondenční adresa: Chytálky 24, Újezd u Tišnova 594 55
Telefon: +420 734 367 351
Email: p.rusinsky@gmail.com
LinkedIn: https://www.linkedin.com/in/pavel-rusinsky/
